[package]
name = "gamething"
version = "0.1.0"
authors = ["Cam Jackson <camjackson89@gmail.com>"]

[dependencies]
piston_window = "0.70.0"
cgmath = "0.15.0"
rustfest-game-assets = { git = "https://github.com/Vurich/rustfest-game-assets.git" }
